apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart-diatte-website.fullname" . }}
  labels:
    {{- include "helm-chart-diatte-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      # nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "helm-chart-diatte-website.selectorLabels" . | nindent 4 }}
